config/routes.rb
# frozen_string_literal: true

ResourceQuotable::Engine.routes.draw do
  resources :quota

  resources :quotum_trackers, only: [] do
    put :reset, on: :member
  end

  root 'quota#index'
end

app/models/resource_quotable/quotum_limit.rb
# == Schema Information
#
# Table name: resource_quotable_quotum_limits
#
#  id        :integer          not null, primary key
#  counter   :integer          default(0), not null
#  flag      :boolean          default(FALSE), not null
#  limit     :integer          default(1), not null
#  period    :integer          default(0), not null
#  quotum_id :integer          not null
#
# Indexes
#
#  index_resource_quotable_quotum_limits_on_quotum_id  (quotum_id)
#

# frozen_string_literal: true

module ResourceQuotable
  # Flag is true when the quota has been reached.
  class QuotumLimit < ApplicationRecord
    belongs_to :quotum

    validates :counter, :limit, :period, presence: true

    scope :with_active_counter, -> { where('counter > 0') }

    enum period: {
      any: 0,
      daily: 1,
      weekly: 2,
      monthly: 3,
      yearly: 4
    }, _suffix: true

    delegate :user, :action, :resource_class, to: :quotum

    def increment!
      raise ResourceQuotable::QuotaLimitError if flag

      new_counter = counter + 1
      update(counter: new_counter, flag: (new_counter >= limit))
    end

    def reset!
      return if counter.zero?

      self.counter = 0
      self.flag = (counter >= limit)
      save

      # I don't like this here.
      quotum.check_flag!
    end
  end
end

app/controllers/resource_quotable/quotum_limits_controller.rb
# frozen_string_literal: true

module ResourceQuotable
  class QuotumLimitsController < ApplicationController # :nodoc:
    layout ResourceQuotable.layout

    before_action :check_authorization
    before_action :load_quotum_limit, only: %i[show edit update destroy]

    def index
      resource_quotable_before
      @page = params[:page] || 1
      @per_page = params[:per_page] || 5

      @quotum_limits = QuotumLimit.page(@page).per(@per_page)
      resource_quotable_after
    end

    def show
      resource_quotable_before
      resource_quotable_after
    end

    def new
      resource_quotable_before
      @quotum_limit = QuotumLimit.new
      @quotum_limit.build_quotum
      resource_quotable_after
    end

    def create
      resource_quotable_before
      @quotum_limit = ResourceQuotable::Create.call(
        user_id: quotum_limit_params[:quotum][:user_id],
        resource: quotum_limit_params[:quotum][:resource_class],
        action: quotum_limit_params[:quotum][:action].to_sym,
        period: quotum_limit_params[:period].to_sym,
        limit: quotum_limit_params[:limit].to_i
      )
      resource_quotable_after
      respond_to do |format|
        format.html do
          flash[:notice] = 'QuotumLimit created'
          redirect_to action: :index
        end
        format.js
      end
    end

    def edit
      resource_quotable_before
      resource_quotable_after
    end

    def update
      resource_quotable_before
      @quotum_limit = ResourceQuotable::Update.call(
        quotum_limit: @quotum_limit,
        limit: quotum_limit_edit_params[:limit].to_i
      )
      resource_quotable_after
      respond_to do |format|
        format.html do
          flash[:notice] = 'QuotumLimit updated'
          redirect_to action: :show, id: @quotum_limit.id
        end
        format.js
      end
    end

    def destroy
      resource_quotable_before
      @id = @quotum_limit.id
      ResourceQuotable::Destroy.call(quotum_limit: @quotum_limit)
      resource_quotable_after
      respond_to do |format|
        format.html do
          flash[:notice] = 'QuotumLimit deleted'
          redirect_to action: :index
        end
        format.js
      end
    end

    protected

    def quotum_limit_params
      params.require(:quotum_limit).permit(
        :period,
        :limit,
        quotum: %i[user_id resource_class action]
      )
    end

    def quotum_limit_edit_params
      params.require(:quotum_limit).permit(:limit)
    end

    def load_quotum_limit
      @quotum_limit = QuotumLimit.find(params[:id])
    end

    def check_authorization
      raise ResourceQuotable::AuthorizationError unless allowed_to_manage_quota?
    end
  end
end

app/views/resource_quotable/quotum_limits/index/_row_content.html.erb
<td><%= link_to quotum_limit.id, quotum_limit_path(quotum_limit), remote: true %></td>
<td><%= quotum_limit.user.name %></td>
<td><%= quotum_limit.resource_class %></td>
<td><%= quotum_limit.action %></td>
<td><%= quotum_limit.period %></td>
<td><%= quotum_limit.limit %></td>
<td><%= quotum_limit.counter %></td>

<td class='text-right'>
  <%= link_to '',
      reset_quotum_limit_path(quotum_limit),
      remote: true,
      method: :put,
      data: {
          confirm: 'Are you sure you want to reset this quotum?',
          tooltip: 'Reset quotum',
          toggle: 'tooltip',
          title: 'Reset quotum',
          placement: 'bottom'
        },
      class: "fa fa-reload" %>
  <%= link_to '',
      edit_quotum_limit_path(quotum_limit),
      remote: true,
      class: 'fa fa-edit',
      data: {
        tooltip: 'Edit',
        title: 'Edit',
        toggle:'tooltip',
        placement: 'left'
      } %>
  <%= link_to '',
      quotum_limit_path(quotum_limit),
      remote: true,
      method: :delete,
      data: {
        confirm: 'Are you sure you want to destroy this quotum?',
        tooltip: 'Delete',
        toggle: 'tooltip',
        title: 'Delete',
        placement: 'left'
      },
      class: 'fa fa-trash' %>
</td>