config/routes.rb
# frozen_string_literal: true

ResourceQuotable::Engine.routes.draw do
  resources :quota

  resources :quotum_trackers, only: [] do
    put :reset, on: :member
  end

  root 'quota#index'
end

app/controllers/resource_quotable/quota_controller.rb
# frozen_string_literal: true

module ResourceQuotable
  class QuotaController < ResourceQuotable::ApplicationController # :nodoc:
    layout ResourceQuotable.layout

    before_action :check_authorization
    before_action :load_quotum, only: %i[show edit update destroy]

    def index
      resource_quotable_before
      @page = params[:page] || 1
      @per_page = params[:per_page] || 5

      @quota = quota_scoped.page(@page).per(@per_page)
      resource_quotable_after
    end

    def show
      resource_quotable_before
      @quotum_trackers = @quotum.quotum_trackers.page(@page).per(@per_page)
      resource_quotable_after
    end

    def new
      resource_quotable_before
      @quotum = Quotum.new
      resource_quotable_after
    end

    def create
      resource_quotable_before
      @quotum = ResourceQuotable::Create.call(
        group: load_quotable_group || default_load_quotable_group,
        resource: quotum_params[:resource_class],
        action: quotum_params[:action].to_sym,
        period: quotum_params[:period].to_sym,
        limit: quotum_params[:limit].to_i
      )
      resource_quotable_after
      respond_to do |format|
        format.html do
          flash[:notice] = 'Quotum created'
          redirect_to action: :index
        end
        format.js
      end
    end

    def edit
      resource_quotable_before
      resource_quotable_after
    end

    def update
      resource_quotable_before
      @quotum = ResourceQuotable::Update.call(
        quotum: @quotum,
        limit: quotum_edit_params[:limit].to_i
      )
      resource_quotable_after
      respond_to do |format|
        format.html do
          flash[:notice] = 'Quotum updated'
          redirect_to action: :show, id: @quotum.id
        end
        format.js
      end
    end

    def destroy
      resource_quotable_before
      @id = @quotum.id
      ResourceQuotable::Destroy.call(quotum: @quotum)
      resource_quotable_after
      respond_to do |format|
        format.html do
          flash[:notice] = 'Quotum deleted'
          redirect_to action: :index
        end
        format.js
      end
    end

    protected

    def quotum_params
      params.require(:quotum).permit(
        :period,
        :limit,
        :resource_class,
        :action,
        :group_id,
        :group_type
      )
    end

    def quotum_edit_params
      params.require(:quotum).permit(:limit)
    end

    def load_quotum
      @quotum = quota_scoped.find(params[:id])
    end
  end
end

app/views/resource_quotable/quota/index/_row.html.erb
<tr id="quotum_<%= quotum.id %>">
  <%= render partial: 'resource_quotable/quota/index/row_content', locals: { quotum: quotum } %>
</tr>

app/views/resource_quotable/quota/index/_row_content.html.erb
<td><%= link_to quotum.id, quotum_path(quotum), remote: true %></td>
<td><%= quotum.user.name %></td>
<td><%= quotum.resource_class %></td>
<td><%= quotum.action %></td>
<td><%= quotum.period %></td>
<td><%= quotum.limit %></td>

<td class='text-right'>
  <%= link_to '',
      reset_quotum_path(quotum),
      remote: true,
      method: :put,
      data: {
          confirm: 'Are you sure you want to reset this quotum?',
          tooltip: 'Reset quotum',
          toggle: 'tooltip',
          title: 'Reset quotum',
          placement: 'bottom'
        },
      class: "fa fa-reload" %>
  <%= link_to '',
      edit_quotum_path(quotum),
      remote: true,
      class: 'fa fa-edit',
      data: {
        tooltip: 'Edit',
        title: 'Edit',
        toggle:'tooltip',
        placement: 'left'
      } %>
  <%= link_to '',
      quotum_path(quotum),
      remote: true,
      method: :delete,
      data: {
        confirm: 'Are you sure you want to destroy this quotum?',
        tooltip: 'Delete',
        toggle: 'tooltip',
        title: 'Delete',
        placement: 'left'
      },
      class: 'fa fa-trash' %>
</td>